### ISSUE TITLE
Do Not Judge Me mode is missing the main graphic

### ISSUE THREAD

**Issue by Sereni** [Sereni/Simply-Love-SM5-Vertical#33]
On the result screen, Pane 1 should be replaced with a cute picture. Follow up with Pluto and include it

**Comment by Roujo** [comment]
I met the Otter of Approval™ today during my set while using `master`, is there an ever _cuter_ picture planned or is this issue solved? =)

**Comment by Sereni** [comment]
The otter is a placeholder — I'm not happy with how a real-life photo looks in a cartoonish UI. Asked Pluto if she'd be able to take on the graphics soon™
