### ISSUE TITLE
Custom global offset requires enter press

### ISSUE THREAD

**Issue by Sereni** [Sereni/Simply-Love-SM5-Vertical#43]
The offset only changes if you press enter after selecting the option, and never do I remember to do that >_>
Fieoner says this is somehow specific to the option being on the 2nd screen, so either find what it is that makes it ignore the "apply on selection" option, or move it to the 1st screen

**Comment by Sereni** [comment]
Bad news:
- All of the options on the 2nd screen require an enter press, which is unintuitive and annoying
- This is also the case in mainline 4.9, so there's nowhere to see how it's supposed to work D:

**Comment by Sereni** [comment]
Or not! Someone with vanilla 4.9 setup just verified it works as expected. Perhaps we broke it in an elaborate way.

**Comment by Roujo** [comment]
I think it has to do with [NavigationMode being set to "toggle"](https://github.com/Sereni/Simply-Love-SM5-Vertical/blob/master/metrics.ini#L687) for that screen? I forgot to test it though, so maybe it's something else. 😅

**Comment by Sereni** [comment]
Duuuuude we don't have medals but you just earned one

**Comment by Sereni** [comment]
Aha, it appears that the toggle mode is there for 3-button navigation, like on DDR cabinets. If that's on, Enter moves on to the next line, and left/right enter the option row and change the value. Without this, 3-button navigation gets stuck on rows with multi-select. Right now it's broken on the first screen on rows Hide, Gameplay Extras, and Measure Counter Options.

One solution to this is to move all multi-select options to the 2nd screen, and move custom global offset up to the 1st screen. Perhaps do it conditionally on 3-button navigation setting (is that possible?) — I'd like to keep the logical layout of the options.

I do wonder if there would be any users limited to 3-button nav AND using vertical.

**Comment by Sereni** [comment]
Actually, has nothing to do with 3 buttons; 4 buttons also break — it's the Stepmania/Arcade style navigation setting.

**Comment by Sereni** [comment]
Interestingly, this doesn't work, because ArcadeOptionsNavigation always resolves to true, regardless of the option value?! But when I SM() the value, it does show 0 and 1 as expected.
`NavigationMode=PREFSMAN:GetPreference("ArcadeOptionsNavigation") and "toggle" or "normal"`

If I use the exact same syntax with ThreeKeyNavigation, it changes the mode correctly.
`NavigationMode=PREFSMAN:GetPreference("ThreeKeyNavigation") and "toggle" or "normal"`

Go figure.
