### ISSUE TITLE
Should Pacemaker be hidden when Do Not Judge Me is enabled?

### ISSUE THREAD

**Issue by Roujo** [Sereni/Simply-Love-SM5-Vertical#49]
I recently pulled in the changes which placed the Pacemaker correctly on-screen (yay!) and I was surprised to see it when I played using Do Not Judge Me today. I understand that Do Not Judge Me mostly affects the judgement screen, but I was expecting it to also hide the Pacemaker since it hides stuff like the best score at song selection. I'm not sure what the intended behavior is here, so before working on it I'd like to know your opinion on this.

Should _Do Not Judge Me_ suppress the display of Pacemaker and other scoring-related gameplay extras when it's on, or is it working as intended and the player should disable those elements manually?

**Comment by Sereni** [comment]
yeah definitely, great catch! I forgot about it when making that change
