### ISSUE TITLE
Update resolution / aspect ratio in settings

### ISSUE THREAD

**Issue by Sereni** [Sereni/Simply-Love-SM5-Vertical#51]
The theme looks bad if the resolution and aspect ratio in Stepmania are not the same as the real values. For example, if our display is 10:16 1440p, and Stepmania thinks it's 3:4 and 960x1280, all UI elements are way, way off.

That said, we don't provide the options for 9:16 and 10:16 and the corresponding resolutions in settings. 

1. Research if it's possible to change the values available in settings, and provide a sensible default
2. If not possible, write a readme section on how to change the values in Preferences.ini
(doesn't Preferences.ini affect all themes? can we set display options per theme?)

**Comment by Sereni** [comment]
Added instructions into readme — can't find an easy way to add an option to the system options row. It goes metrics.ini -> _fallback/metrics.ini, and into "conf" where the rows are read from, but what is conf? Where is conf?..

**Comment by Sereni** [comment]
SL-OperatorMenuOptions.lua might be relevant actually

**Comment by Roujo** [comment]
My _Graphics/Sound Options_ screen shows 9:16 as an available aspect ratio - among many other weird ones, actually. I'm using SM 5.1-beta2 and this theme's `dev` branch. Maybe upgrading SM would be a good solution?

![image](https://user-images.githubusercontent.com/706916/87253139-b2846f80-c446-11ea-808a-a49ef79e6b48.png)
